{% set name = "cfn-flip" %}
{% set version = "1.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/awslabs/aws-cfn-template-flip/archive/{{ version }}.tar.gz
  sha256: c2780f27b74bd14222d19dd82b2b60ca6451c91e5a5ea963758b085bf9dde9ea

build:
  number: 0
  noarch: python
  entry_points:
    - cfn-flip=cfn_flip.main:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - six
  run:
    - click
    - python
    - pyyaml >=4.1
    - six

test:
  imports:
    - cfn_clean
    - cfn_flip
    - cfn_tools
  commands:
    - cfn-flip --help
  requires:
    - pytest >=4.3.0
    - pytest-cov
    - pytest-runner

about:
  home: https://github.com/awslabs/aws-cfn-template-flip
  license: Apache-2.0
  license_family: APACHE
  license_file: 'LICENSE'
  summary: Convert AWS CloudFormation templates between JSON and YAML formats
  doc_url:
  dev_url: https://github.com/awslabs/aws-cfn-template-flip

extra:
  recipe-maintainers:
    - rluria14
    - adbeda
    - agcopenhaver
    - oblute
