travis:
  secure:
    BINSTAR_TOKEN: MBwPTDdNz1BCmRWDhXNEf3JFDK1cQb4Cx+n4EN5HkyrXeKotkADLCfySeJJWnDiTC0QPNLAYu3dEdlQMz/zLuKWxE+Gu3JtCisIgiKXVu5JhIDD1NcfswitvtzZPVHjBWHAzGqiq76rS0a9jq1YItpRISXOQbkLDzDeOb5MQ6qtno5RdFq7t8Be4g3y7AO6caAViOo1bhq+tBrUcnM7iTvwNmQgif5OLxOelVKCNP22cbiFNKMuzPPqY5A8LgwsNIisOX4YzAkY441XqOAgAaiqOt6O5otaaJhp59MYmO/Wqxx+j9c32ObpacrYb4XvtiiGq0Hna5cHN8Lzj0GYhTHDQyVkEt1w3o1YYFciVoNBe1+eM1JxGjH1OQS9ZX0eM3Q+ppzs0Tkr7S4sYUtqkDSETYzWL79ca+vDbedigRp+nsjSsaFCCouJZs2lFUYtP+bZiKwpfAwblGtg0w8mBIJkibsKltHMOpi42Ri5siaCHbYGZ/MgAtpSkeYcaDIvGLN6ENSe9nA2fDgZVXceGqbS+HKhYxQlE3jvinwpOviaCDivHrsTOylL0DkLuaZmlon4rA8IaYXxMbsmTdS3I+CkRdnUkCBz0uPpD7AvYnA9S+SnNe70RRYQ1p96V6AifinSSDPz6NOo2sJP2sizhNw0pGXvcs7sGF9eowpQF6oY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
